#! /bin/bash

# ls
alias ll='ls -alF'
alias la='ls -a'
alias l='ls -CF'

# tail
alias fol='tail -n100 -f'
alias folo='tail -n0 -f'

# git
alias gbv='git branch -v'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gs='git status'
alias gl='git lg -5'
alias ga='git add -p'
alias gft='git fetch $(git rev-parse --symbolic-full-name --abbrev-ref @{u} | tr / " ")'
alias glg='git lg `git rev-parse --abbrev-ref --symbolic-full-name @{u}`^..HEAD'
alias glm='git lg `git merge-base HEAD main`^..HEAD'
alias glms='git lg `git merge-base HEAD master`^..HEAD'
alias gmm='git fetch origin main:main'
alias gmms='git fetch origin master:master'
alias gbak='git cb bak`gbv | grep bak | cut -d"k" -f2 | cut -d" " -f1 | sort -nr | head -n1 | awk "{ print 1 + \\\$1 }"` && git co -'
alias ggone='git for-each-ref --format '"'"'%(refname:short) %(upstream:track)'"'"' | awk '"'"'$2 == "[gone]" {print $1}'"'"' | xargs -r git branch -D'

# github
alias ghpr='git push -u && gh pr create --base main --fill --web'

# other
alias g="grep --color=auto"
alias notrailspace="awk '{gsub(/ +$/,\"\")} {print \$0}'"
alias plz="history | tail -n 2 | colrm 1 7 | head -n 1 | sudo bash"
alias psa="ps aux | head -n1 && ps aux | grep"
alias pathme='export PATH=$(pwd):$PATH'
alias gd="open project.godot && code ."

# enable color support
ls --color=auto &> /dev/null && alias ls='ls --color=auto' || alias ls='ls -G'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
