#! /bin/bash

# ls
alias ll='ls -alF'
alias la='ls -a'
alias l='ls -CF'

# git
alias gbv='git branch -v'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gs='git status'
alias ga='git add -p'
alias gsmall='git ci -am "REBASEME small fix" && git push'
alias gft='git fetch $(git rev-parse --symbolic-full-name --abbrev-ref @{upstream} | sed "s!/! !")'

# python
alias bpy='bpython-curtsies'
alias ipy='ipython'
alias nts='nosetests ./test_*.py'
alias py='python'
alias py3='python3'

# other
alias notrailspace="awk '{gsub(/ +$/,\"\")} {print \$0}'"
alias plz="history | tail -n 2 | colrm 1 7 | head -n 1 | sudo bash"
alias sd="subl ."
alias psa="ps aux | grep --color=auto"

# enable color support
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
