#! /bin/bash

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ]; then
    PATH="$HOME/bin:$PATH"
fi

# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# number of commands remembered
HISTSIZE=1000
# size in lines of the hitory file
HISTFILESIZE=2000

# check the window size after commands, resize if necessary
shopt -s checkwinsize

# "**" matches all files and zero or more directories and subdirectories
shopt -s globstar 2&> /dev/null

# create all of the aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# create all custom functions and their completions
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# export PS1 to custom prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi

# run all other startup scripts
if [ -d ~/.bash_scripts ]; then
    scripts=$(echo ~/.bash_scripts/*.sh);
    for script in $scripts; do
        . $script
    done
fi

export TOOLS=~/tools
export VENV=$TOOLS/venv

# if the user has a local startup script, run it
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi
