#! /bin/bash

# ls
alias ll='ls -alF'
alias la='ls -a'
alias l='ls -CF'
# git
alias gbv='git branch -v'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gs='git status'
alias gc='git commit'
alias ga='git add -p'
# python
alias bpy='bpython-curtsies'
alias nts='nosetests ./test_*.py'
alias py="python"
alias py3="python3"
# other
alias notrailspace="awk '{gsub(/ +$/,\"\")} {print \$0}'"
alias pdfocr="ruby ~/$TOOLS/pdfocr.rb"
# enable color support
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi